import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve } from "pathe";
import { RUNTIME_VERSIONS } from "../runtime-versions.js";

/**
 * Add a module import and `registry.register()` call to `shell/src/main.tsx`.
 * Uses string manipulation rather than AST — the file is generated by the
 * same CLI, so its shape is predictable.
 */
export function addModuleToMain(
  shellDir: string,
  params: { scope: string; moduleName: string; importName: string },
): void {
  const mainPath = resolve(shellDir, "src", "main.tsx");
  let content = readFileSync(mainPath, "utf-8");

  const importLine = `import ${params.importName} from '${params.scope}/${params.moduleName}-module'`;

  // Add the import line right after the last existing import.
  const importLines = content.split("\n").filter((line) => line.startsWith("import "));
  const lastImport = importLines[importLines.length - 1];
  content = content.replace(lastImport, `${lastImport}\n${importLine}`);

  // Add registry.register(...) right after the last existing one. If the
  // shell has none yet (first module), fall back to inserting before
  // `registry.resolve(`.
  const lines = content.split("\n");
  let lastRegisterIndex = -1;
  for (let i = 0; i < lines.length; i++) {
    if (lines[i].includes("registry.register(")) {
      lastRegisterIndex = i;
    }
  }

  if (lastRegisterIndex !== -1) {
    lines.splice(lastRegisterIndex + 1, 0, `registry.register(${params.importName})`);
    content = lines.join("\n");
  } else {
    const resolveMatch = content.match(/^.*registry\.resolve\(/m);
    if (resolveMatch) {
      content = content.replace(
        resolveMatch[0],
        `registry.register(${params.importName})\n\n${resolveMatch[0]}`,
      );
    }
  }

  writeFileSync(mainPath, content);
}

/**
 * Add a module dependency to the shell's `package.json`, sorting deps
 * alphabetically so subsequent additions don't reshuffle the file.
 */
export function addModuleToShellPackageJson(
  shellDir: string,
  params: { scope: string; moduleName: string },
): void {
  const pkgPath = resolve(shellDir, "package.json");
  const pkg = JSON.parse(readFileSync(pkgPath, "utf-8"));

  pkg.dependencies = pkg.dependencies || {};
  pkg.dependencies[`${params.scope}/${params.moduleName}-module`] = "workspace:*";
  pkg.dependencies = sortObject(pkg.dependencies);

  writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + "\n");
}

/**
 * Add a store interface to `app-shared/src/index.ts` and wire it into
 * `AppDependencies`. Anchored on the `// ---- The contract ----` comment
 * and the `export interface AppDependencies` block the templates emit —
 * if either is missing we bail out rather than producing partial,
 * type-broken edits (a store property pointing at a never-declared
 * interface).
 */
export function addStoreToAppShared(
  appSharedDir: string,
  params: { storeName: string; interfaceName: string },
): void {
  const indexPath = resolve(appSharedDir, "src", "index.ts");
  const content = readFileSync(indexPath, "utf-8");

  const marker = "// ---- The contract ----";
  const appDepsAnchor = "export interface AppDependencies";
  if (!content.includes(marker)) {
    throw new Error(
      `Could not find "${marker}" in ${indexPath}. Was the file edited away from the CLI's template?`,
    );
  }
  const appDepsIndex = content.indexOf(appDepsAnchor);
  if (appDepsIndex === -1) {
    throw new Error(
      `Could not find "${appDepsAnchor}" in ${indexPath}. The store cannot be wired without it.`,
    );
  }
  const closingBrace = content.indexOf("}", appDepsIndex);
  if (closingBrace === -1) {
    throw new Error(`Could not find the closing brace of AppDependencies in ${indexPath}.`);
  }

  const storeInterface = `export interface ${params.interfaceName} {\n  // TODO: Add store state and actions\n}\n\n`;
  const withInterface = content.replace(marker, storeInterface + marker);

  // Recompute the closing brace against `withInterface` — the interface
  // we just inserted shifts every offset that follows it.
  const shiftedAppDepsIndex = withInterface.indexOf(appDepsAnchor);
  const shiftedClosingBrace = withInterface.indexOf("}", shiftedAppDepsIndex);
  const before = withInterface.slice(0, shiftedClosingBrace);
  const after = withInterface.slice(shiftedClosingBrace);
  const finalContent = before + `  ${params.storeName}: ${params.interfaceName}\n` + after;

  writeFileSync(indexPath, finalContent);
}

/**
 * Add a store import + entry to `createRegistry({ stores: ... })` in
 * `shell/src/main.tsx`.
 */
export function addStoreToMain(
  shellDir: string,
  params: { storeName: string; importName: string },
): void {
  const mainPath = resolve(shellDir, "src", "main.tsx");
  let content = readFileSync(mainPath, "utf-8");

  const storeImports = content
    .split("\n")
    .filter((line) => /^import \{.*\} from '\.\/stores\//.test(line));
  const lastStoreImport = storeImports[storeImports.length - 1];

  if (lastStoreImport) {
    content = content.replace(
      lastStoreImport,
      `${lastStoreImport}\nimport { ${params.importName} } from './stores/${params.storeName}.js'`,
    );
  }

  const storesMatch = content.match(/stores:\s*\{([^}]+)\}/);
  if (storesMatch) {
    const currentStores = storesMatch[1].trim();
    content = content.replace(
      storesMatch[0],
      `stores: { ${currentStores}, ${params.storeName}: ${params.importName} }`,
    );
  }

  writeFileSync(mainPath, content);
}

/**
 * Add a journey package as a dependency on the shell. Keeps deps sorted.
 */
export function addJourneyToShellPackageJson(
  shellDir: string,
  params: { scope: string; journeyName: string },
): void {
  const pkgPath = resolve(shellDir, "package.json");
  const pkg = JSON.parse(readFileSync(pkgPath, "utf-8"));

  pkg.dependencies = pkg.dependencies || {};
  pkg.dependencies[`${params.scope}/${params.journeyName}-journey`] = "workspace:*";
  // Modules-runtime always carries journeys transitively; the shell still
  // wants a direct dep so it can `import { journeysPlugin }` etc.
  if (!pkg.dependencies["@modular-react/journeys"]) {
    pkg.dependencies["@modular-react/journeys"] = RUNTIME_VERSIONS.journeys;
  }
  pkg.dependencies = sortObject(pkg.dependencies);

  writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + "\n");
}

/**
 * Wire a journey into `shell/src/main.tsx`:
 *   - import the handle + journey (and persistence binding when requested)
 *   - install `journeysPlugin()` via `.use(...)` on the registry (idempotent)
 *   - call `registry.registerJourney(<journey>, { persistence })` (the
 *     options object is omitted entirely when `persistence` isn't supplied)
 *
 * The transform stays string-based: `main.tsx` is generated by this same
 * CLI so its shape is predictable. If a user reformats the file in ways
 * that break these searches, the function is idempotent — re-running
 * after fixing the shape converges.
 */
export function addJourneyToMain(
  shellDir: string,
  params: {
    scope: string;
    journeyName: string;
    journeyExportName: string;
    handleExportName: string;
    /**
     * When set, also import this binding from
     * `./<journeyName>-persistence.js` and pass it to `registerJourney` as
     * `{ persistence }`.
     */
    persistenceExportName?: string;
  },
): void {
  const mainPath = resolve(shellDir, "src", "main.tsx");
  let content = readFileSync(mainPath, "utf-8");

  // 1. Import the journeys plugin if not already imported.
  if (!content.includes("from '@modular-react/journeys'")) {
    const lines = content.split("\n");
    const lastImportIndex = findLastImportIndex(lines);
    lines.splice(
      lastImportIndex + 1,
      0,
      `import { journeysPlugin } from '@modular-react/journeys'`,
    );
    content = lines.join("\n");
  }

  // 2. Import the journey + handle.
  const journeyImport = `import { ${params.journeyExportName}, ${params.handleExportName} } from '${params.scope}/${params.journeyName}-journey'`;
  if (!content.includes(`from '${params.scope}/${params.journeyName}-journey'`)) {
    const lines = content.split("\n");
    const lastImportIndex = findLastImportIndex(lines);
    lines.splice(lastImportIndex + 1, 0, journeyImport);
    content = lines.join("\n");
  }

  // 2b. Import the persistence binding (when --persistence was passed).
  const persistencePath = `./${params.journeyName}-persistence.js`;
  if (params.persistenceExportName && !content.includes(`from '${persistencePath}'`)) {
    const lines = content.split("\n");
    const lastImportIndex = findLastImportIndex(lines);
    lines.splice(
      lastImportIndex + 1,
      0,
      `import { ${params.persistenceExportName} } from '${persistencePath}'`,
    );
    content = lines.join("\n");
  }

  // 3. Install the plugin on the registry. We look for a bare
  //    `createRegistry<...>({...})` call and append `.use(journeysPlugin())`
  //    if no `.use(` is present yet.
  if (!content.includes("journeysPlugin(")) {
    content = content.replace(
      /const registry = createRegistry<([\s\S]+?)>\(([\s\S]*?)\}\)(?!\s*\.use)/,
      (_match, generic: string, body: string) =>
        `const registry = createRegistry<${generic}>(${body}}).use(journeysPlugin())`,
    );
  }

  // 4. Append registerJourney(...) after the last registry.register(...) call.
  //    When persistence is wired, pass the adapter as the second arg so the
  //    runtime actually persists state across reloads.
  const registerCall = params.persistenceExportName
    ? `registry.registerJourney(${params.journeyExportName}, { persistence: ${params.persistenceExportName} })`
    : `registry.registerJourney(${params.journeyExportName})`;
  if (!content.includes(`registerJourney(${params.journeyExportName}`)) {
    const lines = content.split("\n");
    let insertAfter = -1;
    for (let i = 0; i < lines.length; i++) {
      if (
        lines[i].includes("registry.register(") ||
        lines[i].includes("registry.registerJourney(")
      ) {
        insertAfter = i;
      }
    }
    if (insertAfter !== -1) {
      lines.splice(insertAfter + 1, 0, registerCall);
      content = lines.join("\n");
    }
  }

  // 5. Reference the handle in a comment block so a fresh handle import
  //    isn't dead-code-eliminated by the editor's auto-cleaner. Modules
  //    open journeys via `runtime.start(handle, input)` — see
  //    @modular-react/journeys README.
  if (!content.includes(`// Use ${params.handleExportName}`)) {
    content = content.replace(
      `import { ${params.journeyExportName}, ${params.handleExportName} } from`,
      `// Use ${params.handleExportName} (typed token) at call sites: runtime.start(${params.handleExportName}, input).\nimport { ${params.journeyExportName}, ${params.handleExportName} } from`,
    );
  }

  writeFileSync(mainPath, content);
}

/**
 * Ensure `pnpm-workspace.yaml` includes the `journeys/*` glob. The CLI's
 * default workspace template already lists `modules/*` and `app-shared`/
 * `shell`; older projects scaffolded before this command landed get
 * `journeys/*` added on first journey creation.
 *
 * Insertion is anchored on the `packages:` block — we walk only the list
 * items that follow it and stop at the first dedented line. Without that
 * anchor, an `onlyBuiltDependencies:` (or any other) yaml list lower in
 * the file would steal the insertion point and we'd quietly add
 * `journeys/*` under the wrong key.
 */
export function ensureJourneysInWorkspace(projectRoot: string): void {
  const workspacePath = resolve(projectRoot, "pnpm-workspace.yaml");
  if (!existsSync(workspacePath)) return;
  const content = readFileSync(workspacePath, "utf-8");
  if (content.includes("journeys/*")) return;

  const lines = content.split("\n");
  const packagesHeaderIndex = lines.findIndex((line) => /^packages\s*:\s*$/.test(line));
  if (packagesHeaderIndex === -1) return;

  let lastPackagesItemIndex = -1;
  for (let i = packagesHeaderIndex + 1; i < lines.length; i++) {
    const line = lines[i];
    if (/^\s+-\s+/.test(line)) {
      lastPackagesItemIndex = i;
      continue;
    }
    if (line.trim() === "") {
      continue;
    }
    // Any other content (e.g. `onlyBuiltDependencies:`) means the
    // packages block is over.
    break;
  }
  if (lastPackagesItemIndex === -1) return;

  lines.splice(lastPackagesItemIndex + 1, 0, "  - journeys/*");
  writeFileSync(workspacePath, lines.join("\n"));
}

function findLastImportIndex(lines: readonly string[]): number {
  let lastImportIndex = -1;
  for (let i = 0; i < lines.length; i++) {
    if (lines[i].startsWith("import ")) {
      lastImportIndex = i;
    }
  }
  return lastImportIndex;
}

function sortObject<T>(obj: Record<string, T>): Record<string, T> {
  return Object.fromEntries(Object.entries(obj).sort(([a], [b]) => a.localeCompare(b)));
}
