name: Zizmor

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
      - ".github/workflows/zizmor.yml"

permissions: {}

jobs:
  zizmor:
    name: Static analysis of GitHub Actions workflows
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@557e51de59eb14aaaba2ed9621916900a91d50c6 # v6.6.1

      - name: Run zizmor
        run: uvx zizmor --format=sarif . > results.sarif
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@439137e1b50c27ba9e2f9befc93e43091b449c34 # v3.32.0
        with:
          sarif_file: results.sarif
          category: zizmor
